"""
Django settings for vision project.

Generated by "django-admin startproject" using Django 3.9

For more information on this file, see
https://docs.djangoproject.com/en/stable/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/stable/ref/settings/
"""
from dotenv import load_dotenv
load_dotenv()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".

BASE_DIR = Path(__file__).resolve().parent.parent.parent
PROJECT_ROOT = BASE_DIR.parent

import os

LOG_DIR = BASE_DIR / "log"
ARTIFACTS_DIR = PROJECT_ROOT / "artifacts"
MODELS_DIR = ARTIFACTS_DIR / "models"
TMP_DIR = BASE_DIR / "tmp"
MEDIA_ROOT = BASE_DIR / "media"


# Make necessary directories
os.makedirs(LOG_DIR, exist_ok=True)
os.makedirs(TMP_DIR, exist_ok=True)
os.makedirs(MEDIA_ROOT, exist_ok=True)
os.makedirs(MEDIA_ROOT / "move_reports", exist_ok=True)
os.makedirs(MEDIA_ROOT / "newsletter_performance", exist_ok=True)
os.makedirs(MEDIA_ROOT / "newsletter_performance/images", exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "gfm_logformatter": {
            "format": \
                "%(asctime)s\t[%(threadName)s]\t%(levelname)s\t%(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "gfm_logformatter",
        },
        "python_logfile": {
            "class": "logging.FileHandler",
            "formatter": "gfm_logformatter",
            "filename": LOG_DIR / "gfm_vision_python.log",
        },
        "server_logfile": {
            "class": "logging.FileHandler",
            "formatter": "gfm_logformatter",
            "filename": LOG_DIR / "gfm_vision.log",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "server_logfile"],
            "propagate": False,
        },
        "vision.logger": {
            "handlers": ["console", "python_logfile"],
            "level": "INFO",
        },
    },
}

import logging
LOGGER = logging.getLogger("vision.logger")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/stable/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = os.environ["SECRET_KEY"]
except:
    import secrets
    LOGGER.warning("Environment variable 'SECRET_KEY' wasn't set - has been randomly generated.")
    SECRET_KEY = secrets.token_urlsafe(bytes=50)


# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = True
ADMIN_ENABLED = True

ALLOWED_HOSTS = ["*"]


# django-debug-toolbar settings

from debug_toolbar.middleware import show_toolbar

def show_toolbar_to_staff(request):
    return request.user.is_staff and show_toolbar(request)

DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": show_toolbar_to_staff
}


# Application definition

INSTALLED_APPS = [

    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # GFM apps
    "articles",
    "data",
    "data_science",

    # Tables
    "django_tables2",

    # Forms
    "crispy_forms",
    "crispy_bootstrap5",

    # RTF field for article editing
    "djrichtextfield",

    # IP blocking
    "axes",

    # Extensions
    "django_extensions",

]

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesBackend",
    "django.contrib.auth.backends.ModelBackend",
]

MIDDLEWARE = [
    # Django default middleware
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # IP blocking application middleware
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "vision.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "vision.wsgi.application"


# Database
# https://docs.djangoproject.com/en/stable/ref/settings/#databases

DATABASES = {
    "default": {
        "NAME": os.environ["DB_NAME"],
        "USER": os.environ["DB_USER"],
        "PASSWORD": os.environ["DB_PW"],
        "HOST": os.environ["DB_HOST"],
        "PORT": os.environ["DB_PORT"],
        "OPTIONS": {
            "sql_mode": "traditional",
            "charset": "utf8mb4",
        }
    },
}


# Password validation
# https://docs.djangoproject.com/en/stable/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": x,
    }
    for x in [
        "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        "django.contrib.auth.password_validation.MinimumLengthValidator",
        "django.contrib.auth.password_validation.CommonPasswordValidator",
        "django.contrib.auth.password_validation.NumericPasswordValidator",
    ]
]


# Internationalization
# https://docs.djangoproject.com/en/stable/topics/i18n/

LANGUAGE_CODE = "en-gb"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/stable/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_URL = "/static/"

MEDIA_URL = "/media/"


# Default primary key field type
# https://docs.djangoproject.com/en/stable/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CRISPY_TEMPLATE_PACK = "bootstrap5"

DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap.html"

FILE_UPLOAD_HANDLERS = (
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
)

DJRICHTEXTFIELD_CONFIG = {
    "js": ["//cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"],
    "init_template": "djrichtextfield/init/tinymce.js",
    "settings": {
        "menubar": False,
        "plugins": "link image",
        "toolbar": "bold italic | link image | removeformat",
    }
}

LOGIN_URL = "/login"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login"

ADMINS = [
    ("Ben Manson", "ben.manson@globalfundmedia.com"),
    ("Gareth Downing", "gareth.downing@globalfundmedia.com"),
]

MANAGERS = ADMINS


# Email settings

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.office365.com"
EMAIL_HOST_USER = os.environ["MS_USER"]
EMAIL_HOST_PASSWORD = os.environ["MS_PW"]
EMAIL_PORT = 587
EMAIL_USE_TLS = True
