# Generated by Django 4.0.4 on 2022-06-01 10:22

import articles.fields
import bitfield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, db_column='title', null=True)),
                ('content', articles.fields.MediumTextField(blank=True, db_column='content', null=True)),
                ('author', models.CharField(blank=True, db_column='author', max_length=100, null=True)),
                ('url', models.CharField(blank=True, db_column='url', max_length=255, null=True)),
                ('source', models.CharField(blank=True, db_column='source', max_length=255, null=True)),
                ('tags', models.CharField(blank=True, db_column='tags', max_length=255, null=True)),
                ('publish_date', models.DateField(db_column='publish_date')),
                ('publish', models.BooleanField(db_column='publish', default=0)),
                ('editorial_title', bitfield.models.BitField([(0, '—'), (1, 'HW'), (2, 'HW (?)'), (3, 'PEW'), (4, 'PEW (?)')], db_column='editorial_title', default=None)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
