# Generated by Django 4.0.7 on 2022-09-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='editorial_title',
            field=models.IntegerField(choices=[(0, '—'), (1, 'HW'), (2, 'HW (?)'), (3, 'PEW'), (4, 'PEW (?)')], db_column='editorial_title', default=0),
        ),
    ]
