# Generated by Django 4.0.7 on 2022-09-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_editorial_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='kind',
            field=models.CharField(choices=[('—', '—'), ('Meltwater', 'Meltwater'), ('Google Alerts', 'Google Alerts')], db_column='kind', default=None, max_length=50),
        ),
    ]
