# Generated by Django 4.0.7 on 2022-10-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='editorial_title',
            field=models.CharField(choices=[('—', '—'), ('HW', 'HW'), ('PEW', 'PEW'), ('HW (?)', 'HW (?)'), ('PEW (?)', 'PEW (?)')], db_column='editorial_title', default=None, max_length=50),
        ),
    ]
