# Generated by Django 4.0.7 on 2022-09-06 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('cleaned_name', models.CharField(db_column='cleaned_name', max_length=255)),
                ('linkedin_url', models.CharField(db_column='linkedin_url', max_length=255, unique=True)),
                ('aum_category', models.IntegerField(db_column='aum_category', default=0)),
                ('raum', models.FloatField(db_column='raum', default=0)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='FirmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_type', models.CharField(choices=[('HF Manager', 'HF Manager'), ('PM Manager', 'PM Manager'), ('Allocator', 'Allocator'), ('HF Service Provider', 'HF Service Provider'), ('PM Fund Service Provider', 'PM Fund Service Provider'), ('Equity', 'Equity'), ('Credit', 'Credit'), ('Global macro', 'Global macro'), ('Relative value', 'Relative value'), ('CTA', 'CTA'), ('Event-driven', 'Event-driven'), ('Multi-strategy', 'Multi-strategy'), ('Digital assets', 'Digital assets'), ('Other', 'Other'), ('Private equity', 'Private equity'), ('Venture capital', 'Venture capital'), ('Real estate', 'Real estate'), ('Infrastructure', 'Infrastructure'), ('Private credit/debt', 'Private credit/debt'), ('Bank platform/Wealth manager', 'Bank platform/Wealth manager'), ('Corporate investor', 'Corporate investor'), ('Endowment/Foundation', 'Endowment/Foundation'), ('Fund of funds', 'Fund of funds'), ('Sovereign wealth fund', 'Sovereign wealth fund'), ('Insurance', 'Insurance'), ('Pension', 'Pension'), ('Family office', 'Family office'), ('Investment consultant', 'Investment consultant'), ('Administrator', 'Administrator'), ('Legal and compliance', 'Legal and compliance'), ('Prime broker', 'Prime broker'), ('Tax and audit', 'Tax and audit'), ('Custody', 'Custody'), ('Technology', 'Technology'), ('Advisory', 'Advisory'), ('Financing services', 'Financing services'), ('Quantitative', 'Quantitative')], db_column='value', max_length=50, unique=True)),
                ('is_subtype', models.BooleanField(db_column='subtype', default=1)),
            ],
            options={
                'db_table': 'firmtype',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CEO', 'CEO'), ('COO', 'COO'), ('CTO', 'CTO'), ('CFO', 'CFO'), ('CIO', 'CIO'), ('CCO', 'CCO'), ('Product', 'Product'), ('Operations and finance', 'Operations and finance'), ('Technology', 'Technology'), ('Front office and investment', 'Front office and investment'), ('Legal and compliance', 'Legal and compliance'), ('Sales/IR', 'Sales/IR'), ('C-suite', 'C-suite'), ('Head of department', 'Head of department')], db_column='value', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'jobcategory',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_column='firstname', max_length=50)),
                ('lastname', models.CharField(db_column='lastname', max_length=50)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=50, unique=True)),
                ('domain', models.CharField(db_column='domain', max_length=255)),
            ],
            options={
                'db_table': 'social',
                'unique_together': {('name', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street1', models.CharField(db_column='street1', max_length=50)),
                ('street2', models.CharField(db_column='street2', max_length=50)),
                ('city', models.CharField(db_column='city', max_length=25)),
                ('state_county', models.CharField(db_column='state_county', max_length=20)),
                ('postalcode', models.CharField(db_column='postalcode', max_length=12)),
                ('country', models.CharField(db_column='country', max_length=50)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=50)),
                ('source', models.CharField(db_column='source', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.company')),
            ],
            options={
                'db_table': 'company_contact',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(db_column='company', max_length=255)),
                ('role', models.CharField(db_column='role', max_length=100)),
                ('location', models.CharField(db_column='location', max_length=100)),
                ('date_started', models.DateField(db_column='date_started')),
                ('date_ended', models.DateField(db_column='date_ended')),
                ('source', models.CharField(db_column='source', max_length=20)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('company_obj', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='data.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.person')),
            ],
            options={
                'db_table': 'career',
                'unique_together': {('person', 'company', 'role', 'date_started')},
            },
        ),
        migrations.CreateModel(
            name='PersonSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_column='value', max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.person')),
                ('social_media', models.ForeignKey(db_column='social_id', on_delete=django.db.models.deletion.CASCADE, to='data.socialmedia')),
            ],
            options={
                'db_table': 'person_social',
                'unique_together': {('person', 'value')},
            },
        ),
        migrations.CreateModel(
            name='PersonPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_column='value', max_length=255)),
                ('source', models.CharField(db_column='source', max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.person')),
            ],
            options={
                'db_table': 'person_telephone',
                'unique_together': {('person', 'value', 'source')},
            },
        ),
        migrations.CreateModel(
            name='PersonEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_column='value', max_length=255)),
                ('source', models.CharField(db_column='source', max_length=50)),
                ('confidence', models.FloatField(db_column='confidence', default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.person')),
            ],
            options={
                'db_table': 'person_email',
                'unique_together': {('person', 'value', 'source')},
            },
        ),
        migrations.CreateModel(
            name='CompanyWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_column='value', max_length=255)),
                ('source', models.CharField(db_column='source', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.company')),
            ],
            options={
                'db_table': 'company_website',
                'unique_together': {('company', 'value', 'source')},
            },
        ),
        migrations.CreateModel(
            name='CompanyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(db_column='child_company_id', on_delete=django.db.models.deletion.CASCADE, related_name='child', to='data.company')),
                ('parent', models.ForeignKey(db_column='parent_company_id', on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='data.company')),
            ],
            options={
                'db_table': 'company_relation',
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.CreateModel(
            name='CompanyFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_format', models.CharField(choices=[('first.last', 'first.last'), ('first', 'first'), ('flast', 'flast'), ('fl', 'fl'), ('firstlast', 'firstlast'), ('f.last', 'f.last'), ('first_last', 'first_last'), ('firstl', 'firstl'), ('last', 'last'), ('f.l', 'f.l'), ('lastfirst', 'lastfirst'), ('lastf', 'lastf'), ('last.first', 'last.first'), ('first.l', 'first.l'), ('fla', 'fla')], db_column='email_format', max_length=25)),
                ('domain', models.CharField(db_column='domain', max_length=50)),
                ('confidence', models.FloatField(db_column='confidence', default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.company')),
            ],
            options={
                'db_table': 'company_format',
                'unique_together': {('company_id', 'email_format', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='CompanyFirmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.company')),
                ('firm_type', models.ForeignKey(db_column='firmtype_id', on_delete=django.db.models.deletion.CASCADE, to='data.firmtype')),
            ],
            options={
                'db_table': 'company_firmtype',
                'unique_together': {('company', 'firm_type')},
            },
        ),
        migrations.CreateModel(
            name='CareerJobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.career')),
                ('jobcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.jobcategory')),
            ],
            options={
                'db_table': 'career_jobcategory',
                'unique_together': {('career', 'jobcategory')},
            },
        ),
    ]
