# Generated by Django 4.0.4 on 2022-06-01 10:14

from django.db import migrations

DEFAULT_FIRMTYPES = (
    ('HF Manager', 0),
    ('PM Manager', 0),
    ('Allocator', 0),
    ('HF Service Provider', 0),
    ('PM Fund Service Provider', 0),
    ('Equity', 1),
    ('Credit', 1),
    ('Global macro', 1),
    ('Relative value', 1),
    ('CTA', 1),
    ('Event-driven', 1),
    ('Multi-strategy', 1),
    ('Digital assets', 1),
    ('Other', 1),
    ('Private equity', 1),
    ('Venture capital', 1),
    ('Real estate', 1),
    ('Infrastructure', 1),
    ('Private credit/debt', 1),
    ('Bank platform/Wealth manager', 1),
    ('Corporate investor', 1),
    ('Endowment/Foundation', 1),
    ('Fund of funds', 1),
    ('Sovereign wealth fund', 1),
    ('Insurance', 1),
    ('Pension', 1),
    ('Family office', 1),
    ('Investment consultant', 1),
    ('Administrator', 1),
    ('Legal and compliance', 1),
    ('Prime broker', 1),
    ('Tax and audit', 1),
    ('Custody', 1),
    ('Technology', 1),
    ('Advisory', 1),
    ('Financing services', 1),
    ('Quantitative', 1)
)

DEFAULT_JOBCATEGORIES = [
    'Front office and investment',
    'Legal and compliance',
    'Operations and finance',
    'Sales/IR',
    'Technology'
]

DEFAULT_SOCIALS = (
    ('Linkedin', 'https://www.linkedin.com'),
    ('Facebook', 'https://www.facebook.com'),
    ('Twitter', 'https://twitter.com'),
    ('Instagram', 'https://instagram.com'),
)

def add_firmtype(apps, schema_editor):
    FirmType = apps.get_model('data', 'FirmType')

    for value, is_subtype in DEFAULT_FIRMTYPES:
        firm_type, _ = FirmType.objects.get_or_create(firm_type=value, is_subtype=is_subtype)
        firm_type.save()

def remove_firmtype(apps, schema_editor):
    FirmType = apps.get_model('data', 'FirmType')

    for firm_type in FirmType.objects.all():
        firm_type.delete()

def add_jobcategory(apps, schema_editor):
    JobCategory = apps.get_model('data', 'JobCategory')

    for value in DEFAULT_JOBCATEGORIES:
        job_category, _ = JobCategory.objects.get_or_create(category=value)
        job_category.save()

def remove_jobcategory(apps, schema_editor):
    JobCategory = apps.get_model('data', 'JobCategory')

    for job_category in JobCategory.objects.all():
        job_category.delete()

def add_socialmedia(apps, schema_editor):
    SocialMedia = apps.get_model('data', 'SocialMedia')

    for name, domain in DEFAULT_SOCIALS:
        social_media, _ = SocialMedia.objects.get_or_create(name=name, domain=domain)
        social_media.save()

def remove_socialmedia(apps, schema_editor):
    SocialMedia = apps.get_model('data', 'SocialMedia')

    for social_media in SocialMedia.objects.all():
        social_media.delete()

def create_defaultcompany(apps, schema_editor):
    Company = apps.get_model('data', 'Company')

    obj = Company(pk=-1)
    obj.save()

def remove_defaultcompany(apps, schema_editor):
    Company = apps.get_model('data', 'Company')

    obj = Company.objects.get(pk=-1)
    obj.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_firmtype, remove_firmtype),
        migrations.RunPython(add_jobcategory, remove_jobcategory),
        migrations.RunPython(add_socialmedia, remove_socialmedia),
        migrations.RunPython(create_defaultcompany, remove_defaultcompany),
        migrations.RunSQL("""
        CREATE OR REPLACE VIEW contacts AS
            SELECT
                `vision`.`person`.`firstname` AS `firstname`,
                `vision`.`person`.`lastname` AS `lastname`,
                `vision`.`career`.`role` AS `role`,
                `vision`.`career`.`company` AS `company_name`,
                `vision`.`person_social`.`value` AS `linkedin_profile`,
                `vision`.`career`.`date_started` AS `date_started`,
                `vision`.`career`.`date_ended` AS `date_ended`,
                `vision`.`career`.`id` AS `career_id`,
                `vision`.`career`.`person_id` AS `person_id`,
                `vision`.`career`.`company_id` AS `company_id`
            FROM
                (
                    (
                        (
                            `vision`.`career`
                            JOIN `vision`.`person` ON(
                                (
                                    `vision`.`person`.`id` = `vision`.`career`.`person_id`
                                )
                            )
                        )
                        JOIN `vision`.`person_social` ON(
                            (
                                `vision`.`person_social`.`person_id` = `vision`.`career`.`person_id`
                            )
                        )
                    )
                    JOIN `vision`.`company` ON(
                        (
                            `vision`.`company`.`id` = `vision`.`career`.`company_id`
                        )
                    )
                )
        """, 'DROP VIEW contacts;'),
    ]
