# Generated by Django 4.0.7 on 2022-09-08 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20220601_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLinkedin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_column='value', max_length=255, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.company')),
            ],
            options={
                'db_table': 'company_linkedin',
            },
        ),
    ]
