# Generated by Django 4.0.7 on 2022-09-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_companylinkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gfm_company_id',
            field=models.CharField(db_column='gfm_company_id', default='', max_length=50),
        ),
    ]
