# Generated by Django 4.0.7 on 2022-09-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_company_gfm_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='gfm_move_id',
            field=models.CharField(db_column='gfm_move_id', default='', max_length=50),
        ),
    ]
