# Generated by Django 4.0.7 on 2022-09-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_career_gfm_move_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='linkedin_url',
        ),
    ]
