# Generated by Django 4.0.7 on 2022-09-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_company_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='company',
            field=models.CharField(db_column='company', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='cleaned_name',
            field=models.CharField(db_column='cleaned_name', db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_column='name', db_index=True, max_length=255),
        ),
    ]
