# Generated by Django 4.0.7 on 2022-09-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_career_company_alter_company_cleaned_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='aum_bracket',
            field=models.IntegerField(db_column='aum_bracket', default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='specialism',
            field=models.CharField(choices=[('Activist', 'Activist'), ('Credit', 'Credit'), ('Debt', 'Debt'), ('Digital Assets', 'Digital Assets'), ('Equity', 'Equity'), ('Event-driven', 'Event-driven'), ('Futures', 'Futures'), ('Macro', 'Macro'), ('Multi-strategy', 'Multi-strategy'), ('Niche', 'Niche'), ('Quant', 'Quant'), ('Various', 'Various')], db_column='specialism', default=None, max_length=50),
        ),
    ]
