# Generated by Django 4.0.7 on 2022-09-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_company_aum_bracket_company_specialism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='specialism',
            field=models.CharField(choices=[('—', '—'), ('Activist', 'Activist'), ('Credit', 'Credit'), ('Debt', 'Debt'), ('Digital Assets', 'Digital Assets'), ('Equity', 'Equity'), ('Event-driven', 'Event-driven'), ('Futures', 'Futures'), ('Macro', 'Macro'), ('Multi-strategy', 'Multi-strategy'), ('Niche', 'Niche'), ('Quant', 'Quant'), ('Various', 'Various')], db_column='specialism', default=None, max_length=50, null=True),
        ),
    ]
