# Generated by Django 4.1.2 on 2022-11-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_company_specialism'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMappings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preqin_id', models.CharField(blank=True, default='', max_length=100)),
                ('active_campaign_id', models.CharField(blank=True, default='', max_length=100)),
                ('zoho_id', models.CharField(blank=True, default='', max_length=100)),
                ('company', models.OneToOneField(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, to='data.company')),
            ],
            options={
                'db_table': 'company_mapping',
            },
        ),
    ]
