# Generated by Django 4.1.2 on 2022-11-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_companymappings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='category',
            field=models.CharField(choices=[('Front office and investment', 'Front office and investment'), ('Legal and compliance', 'Legal and compliance'), ('Operations and finance', 'Operations and finance'), ('Sales/IR', 'Sales/IR'), ('Technology', 'Technology')], db_column='value', max_length=50, unique=True),
        ),
    ]
